# Generated by Django 5.0.1 on 2024-02-03 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=15)),
                ('razon_social', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('domicilio_fiscal', models.CharField(max_length=100)),
                ('distrito', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edificio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LineaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='solicitudes/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negocio', models.CharField(max_length=50)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.lineanegocio')),
            ],
        ),
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piso', models.CharField(max_length=30)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
                ('piso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.piso')),
                ('tipo_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.tipoequipo')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='edificio',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.sede'),
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limpieza', models.BooleanField()),
                ('inspeccion', models.BooleanField()),
                ('lubricacion', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.equipo')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.negocio')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.solicitud')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.tipodocumento'),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=30)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.area')),
                ('jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.trabajador')),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.tiposervicio')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Refrimotors.trabajador'),
        ),
    ]
