# Generated by Django 5.0.1 on 2024-02-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vicamar', '0003_alquiler_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='pdf_url',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones/'),
        ),
    ]
