# Generated by Django 5.0.1 on 2024-02-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vicamar', '0004_alquiler_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='descuento',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
