# Generated by Django 5.0.1 on 2024-02-06 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vicamar', '0005_alter_alquiler_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
